[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NITRO_PRESET = "netlify-edge"
  NODE_VERSION = "22"

[[redirects]]
  from = "/*"
  to = "/.netlify/edge-functions/server"
  status = 200
